-- ============================================
-- DEV CRAFT AGENT — ONE-TIME SUPABASE SETUP (v8)
-- Naya Supabase project? Ye POORA SQL ek baar
-- SQL Editor (Dashboard > SQL Editor) mein paste
-- karke RUN karo — saari tables ban jayengi.
-- ============================================

-- 1) LEADS (business leads database)
create table if not exists leads (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  city text,
  email text,
  phone text,
  website text,
  audit_score int,
  lead_score int,
  status text default 'new',
  notes text,
  created_at timestamptz default now()
);

-- 2) AUTOMATIONS ("roz karo" daily 9AM PKT)
create table if not exists automations (
  id bigint generated by default as identity primary key,
  name text not null,
  prompt text not null,
  schedule text default 'daily',
  active boolean default true,
  created_at timestamptz default now()
);

-- 3) PC BRIDGE (device pairing + jobs)
create table if not exists bridge_devices (
  id uuid default gen_random_uuid() primary key,
  code text,
  device_name text,
  os text,
  status text default 'pairing',
  ollama_models jsonb default '[]',
  last_seen timestamptz,
  created_at timestamptz default now()
);
create table if not exists bridge_jobs (
  id uuid default gen_random_uuid() primary key,
  device_id uuid references bridge_devices(id),
  type text,
  payload jsonb,
  status text default 'pending',
  result jsonb,
  created_at timestamptz default now()
);

-- 4) CREDENTIAL VAULT (per-user encrypted tokens)
--    HAR USER ka apna vault (user_id se alag).
create table if not exists credentials (
  id bigint generated by default as identity primary key,
  user_id text not null default 'owner',
  name text not null,
  value_enc text not null,
  iv text not null,
  tag text not null,
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

-- 5) MCP SERVERS (per-user connected MCP servers)
--    token_enc/iv/tag = encrypted MCP auth token (service-role only)
create table if not exists mcp_servers (
  id bigint generated by default as identity primary key,
  user_id text not null default 'owner',
  name text not null,
  url text not null,
  token_enc text,
  token_iv text,
  token_tag text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

-- ============================================
-- OPTIONAL (recommended jab Google auth on ho):
-- mcp_servers + credentials pe RLS — users sirf
-- apni rows dekh sakein. Server service-role key
-- use karta hai is liye RLS usko rokta nahi.
-- ============================================
-- alter table credentials enable row level security;
-- alter table mcp_servers enable row level security;
-- create policy "own creds" on credentials for all
--   using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
-- create policy "own mcp" on mcp_servers for all
--   using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
