// ============================================
// CREDENTIAL VAULT (shared helper) - server/lib/credentials.js
// Solene-style token system: user koi bhi token/key
// chat ya API se save kare => AES-256-GCM se encrypt
// karke Supabase "credentials" table mein rakhta hai.
// getCredential() pehle DB dhoondta hai, phir env var
// fallback deta hai - is liye purane endpoints bhi
// bina badle chalte rahenge.
//
// SUPABASE SQL (SQL Editor mein chalao):
//   create table credentials (
//     id bigint generated by default as identity primary key,
//     user_id text not null default 'owner',
//     name text not null,
//     iv text not null,
//     tag text not null,
//     description text,
//     created_at timestamptz default now(),
//     updated_at timestamptz default now(),
//     unique (user_id, name)
//   );
// HAR USER (browser device / WhatsApp number / Telegram id)
// ka apna alag vault - ek user ka token doosre ko nahi milta.
//
// ENV (optional but recommended):
//   CREDENTIALS_SECRET = lamba random string (32+ chars)
//   (missing ho to Supabase anon key se derive hota hai)
// ============================================
const crypto = require('crypto');

function masterKey() {
  const secret = process.env.CREDENTIALS_SECRET || (process.env.SUPABASE_ANON_KEY || 'dev-craft-agent') + '::vault-fallback';
  return crypto.scryptSync(secret, 'dev-craft-vault-v1', 32);
}

function encrypt(value) {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', masterKey(), iv);
  const enc = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]);
  return { value_enc: enc.toString('base64'), iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64') };
}

function decrypt(row) {
  try {
    const decipher = crypto.createDecipheriv('aes-256-gcm', masterKey(), Buffer.from(row.iv, 'base64'));
    decipher.setAuthTag(Buffer.from(row.tag, 'base64'));
    return Buffer.concat([decipher.update(Buffer.from(row.value_enc, 'base64')), decipher.final()]).toString('utf8');
  } catch (e) {
    return null; // galat CREDENTIALS_SECRET ya corrupt data
  }
}

function mask(value) {
  const v = String(value || '');
  if (v.length <= 8) return v ? '••••' : '';
  return v.slice(0, 4) + '••••' + v.slice(-4);
}

function uid(userId) { return String(userId || 'owner').trim() || 'owner'; }

function sb() {
  const SB_URL = process.env.SUPABASE_URL, SB_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY; // RLS-safe: service role bypass karta hai
  if (!SB_URL || !SB_KEY) return null;
  return { url: SB_URL, headers: { 'apikey': SB_KEY, 'Authorization': 'Bearer ' + SB_KEY, 'Content-Type': 'application/json' } };
}

function noSupabase() {
  return { error: 'Supabase missing', setup_help: 'Vault ke liye Supabase chahiye: supabase.com pe free project banao, "credentials" table banao (SQL README mein hai), SUPABASE_URL + SUPABASE_ANON_KEY set karo. Alternative: .env vars set karo (vahi purana tareeqa).' };
}

// ---------- public API ----------

// value save karo (upsert). returns {ok, saved, masked} ya {error}
async function saveCredential(name, value, description, userId) {
  const s = sb(); if (!s) return noSupabase();
  if (!name || !value) return { error: 'name aur value dono chahiye' };
  const U = uid(userId);
  const { value_enc, iv, tag } = encrypt(value);
  const r = await fetch(s.url + '/rest/v1/credentials?on_conflict=user_id,name', {
    method: 'POST',
    headers: { ...s.headers, Prefer: 'resolution=merge-duplicates' },
    body: JSON.stringify({ user_id: U, name: String(name).toUpperCase().trim(), value_enc, iv, tag, description: description || null, updated_at: new Date().toISOString() })
  });
  return r.ok ? { ok: true, user_id: U, saved: String(name).toUpperCase().trim(), masked: mask(value) } : { error: 'Supabase save fail (HTTP ' + r.status + ') - credentials table bani hai? (unique (user_id, name) bhi chahiye)' };
}

// decrypted value lo; DB mein na mile to env var fallback
async function getCredential(name, userId) {
  const n = String(name || '').trim();
  if (!n) return null;
  const s = sb();
  if (s) {
    try {
      const q = 'user_id=eq.' + encodeURIComponent(uid(userId)) + '&name=eq.' + encodeURIComponent(n.toUpperCase());
      const r = await fetch(s.url + '/rest/v1/credentials?' + q + '&select=name,value_enc,iv,tag', { headers: s.headers });
      if (r.ok) {
        const rows = await r.json();
        if (rows && rows[0]) {
          const v = decrypt(rows[0]);
          if (v) return v;
        }
      }
    } catch (e) { /* network fail => env fallback */ }
  }
  return process.env[n] || null;
}

// masked list (values kabhi nahi dikhti)
async function listCredentials(userId) {
  const s = sb(); if (!s) return noSupabase();
  const U = uid(userId);
  const r = await fetch(s.url + '/rest/v1/credentials?user_id=eq.' + encodeURIComponent(U) + '&select=name,description,created_at,updated_at&order=updated_at.desc', { headers: s.headers });
  if (!r.ok) return { error: 'Supabase read fail (HTTP ' + r.status + ')' };
  const rows = await r.json();
  return { user_id: U, credentials: (rows || []).map(row => ({ name: row.name, description: row.description, masked: '••••', updated_at: row.updated_at, source: 'vault' })) };
}

async function deleteCredential(name, userId) {
  const s = sb(); if (!s) return noSupabase();
  const U = uid(userId);
  const r = await fetch(s.url + '/rest/v1/credentials?user_id=eq.' + encodeURIComponent(U) + '&name=eq.' + encodeURIComponent(String(name).toUpperCase().trim()), { method: 'DELETE', headers: s.headers });
  return r.ok ? { ok: true, deleted: String(name).toUpperCase().trim() } : { error: 'delete fail (HTTP ' + r.status + ')' };
}

// raw text encrypt/decrypt (MCP server tokens waghera ke liye)
function encryptText(v) { return encrypt(v); }
function decryptText(e, i, t) { return decrypt({ value_enc: e, iv: i, tag: t }); }

module.exports = { saveCredential, getCredential, listCredentials, deleteCredential, mask, noSupabase, encryptText, decryptText };
